### ISSUE TITLE
This code is based to esp now and have max 250 byte? 

### ISSUE THREAD

**Issue by cent0** [Tommy270502/ESP32_ESPNOW-Communication#1]
In need extend Comunication for master and slave but have 355byte and 55byte speed 9600baud do you have any idea? 

I have found this info online
https://stackoverflow.com/questions/60879021/how-to-increase-rx-serial-buffer-size-for-esp32-library-hardwareserial-platform
Thank you

**Comment by Tommy270502** [comment]
Hello the link you sent is related to USB serial and not ESPNOW. Please refer to Espressif systems for detailed questions.

**Comment by cent0** [comment]
I need use this? Compatible with esp8266?
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/uart.html

**Comment by Tommy270502** [comment]
No UART is a protocol over cable connection.

Espnow is a wireless protocol.

On the espressif website there is a pdf called:[ESP-NOW User Guide](https://www.espressif.com/en/products/software/esp-now/resources)

Inside the pdf espressif systems state that the esp-now protocol il linited to 250byte payload size.

**Comment by cent0** [comment]
Tommy I need help for transmit 350byte and 50
I have this log one wire 350 and other 50
![Videoframe_20221024_213645_com huawei himovie overseas](https://user-images.githubusercontent.com/39629876/197611769-d075b6a0-ca64-46ac-b693-32be8ee53c40.jpg)

**Comment by cent0** [comment]
> No UART is a protocol over cable connection.
> 
> Espnow is a wireless protocol.
> 
> On the espressif website there is a pdf called:[ESP-NOW User Guide](https://www.espressif.com/en/products/software/esp-now/resources)
> 
> Inside the pdf espressif systems state that the esp-now protocol is limited to 250byte payload size.

{MCUMAINBOARD} {ESP} WIFI{ESP} {MCUBOARDDISPLAY)
